name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      location:
        description: 'Azure region to deploy to'
        required: true
        default: 'eastus'
        type: string

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Validate ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/arm-templates/azure-resources.json
          parameters: ./infrastructure/arm-templates/parameters/${{ github.event.inputs.environment }}.parameters.json
          deploymentName: validate-fbwordle-${{ github.event.inputs.environment }}-${{ github.run_number }}
          deploymentMode: Validate
          
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/arm-templates/azure-resources.json
          parameters: ./infrastructure/arm-templates/parameters/${{ github.event.inputs.environment }}.parameters.json
          deploymentName: deploy-fbwordle-${{ github.event.inputs.environment }}-${{ github.run_number }}
          deploymentMode: Incremental
          
      - name: Get Deployment Outputs
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/arm-templates/azure-resources.json
          parameters: ./infrastructure/arm-templates/parameters/${{ github.event.inputs.environment }}.parameters.json
          deploymentName: output-fbwordle-${{ github.event.inputs.environment }}-${{ github.run_number }}
          deploymentMode: Validate
          
      - name: Output Deployment Information
        run: |
          echo "Static Web App URL: https://${{ steps.deploy.outputs.staticWebAppHostName }}"
          echo "Function App URL: https://${{ steps.deploy.outputs.functionAppHostName }}"
          echo "Static Web App Name: ${{ steps.deploy.outputs.staticWebAppName }}"
          echo "Function App Name: ${{ steps.deploy.outputs.functionAppName }}"
          echo "Cosmos DB Endpoint: ${{ steps.deploy.outputs.cosmosDbEndpoint }}"
