name: Deploy Function App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      location:
        description: 'Azure region to deploy to'
        required: true
        default: 'eastus'
        type: string

jobs:
  deploy-function-app:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get Static Web App URL
        id: get-swa-url
        run: |
          SWA_URL=$(az staticwebapp show --name "${{ secrets.STATIC_WEB_APP_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" --query "defaultHostname" -o tsv)
          echo "url=https://${SWA_URL}" >> $GITHUB_OUTPUT
          echo "staticWebAppUrl=https://${SWA_URL}" >> $GITHUB_OUTPUT
        
      - name: Get Cosmos DB Connection String
        id: get-cosmos-db
        run: |
          CONNECTION_STRING=$(az cosmosdb keys list --type connection-strings --name "${{ secrets.COSMOS_DB_ACCOUNT_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" --query "connectionStrings[0].connectionString" -o tsv)
          echo "::add-mask::$CONNECTION_STRING"
          echo "connection_string=${CONNECTION_STRING}" >> $GITHUB_OUTPUT
          echo "cosmosDbConnectionString=${CONNECTION_STRING}" >> $GITHUB_OUTPUT
          
      - name: Deploy Function App ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/arm-templates/function-app.json
          parameters: ./infrastructure/arm-templates/parameters/function-app-${{ github.event.inputs.environment }}.parameters.json cosmosDbConnectionString="${{ steps.get-cosmos-db.outputs.connection_string }}" staticWebAppUrl="${{ steps.get-swa-url.outputs.url }}"
          deploymentName: deploy-fbwordle-function-${{ github.event.inputs.environment }}-${{ github.run_number }}
          deploymentMode: Incremental
          
      - name: Get Function App Deployment Output
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/arm-templates/function-app.json
          parameters: ./infrastructure/arm-templates/parameters/function-app-${{ github.event.inputs.environment }}.parameters.json cosmosDbConnectionString="${{ steps.get-cosmos-db.outputs.connection_string }}" staticWebAppUrl="${{ steps.get-swa-url.outputs.url }}"
          deploymentName: output-fbwordle-function-${{ github.event.inputs.environment }}-${{ github.run_number }}
          deploymentMode: Validate
          
      - name: Output Deployment Information
        run: |
          echo "Function App URL: https://${{ steps.deploy.outputs.functionAppHostName }}"
          echo "Function App Name: ${{ steps.deploy.outputs.functionAppName }}"
          echo "Storage Account: ${{ steps.deploy.outputs.storageAccountName }}"
          echo "App Service Plan: ${{ steps.deploy.outputs.appServicePlanName }}"
          echo "Application Insights: ${{ steps.deploy.outputs.appInsightsName }}"
